repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0  # Change to the latest Black version
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --ignore=F401]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

# mypy: Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2  # Latest stable version
    hooks:
      - id: mypy
        args:
          - "--ignore-missing-imports"

# pydocstyle: Docstring convention checking (PEP 257)
  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 6.3.0  # Latest stable version
  #   hooks:
  #     - id: pydocstyle

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: ./.venv/bin/pytest tests
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
